<?php
/** Deutsche Oberflächentexte. DOCS.md 4.6, 11.3 */
declare(strict_types=1);
return [
 'skip_to_content'=>'Zum Inhalt springen','menu'=>'Menü','open_menu'=>'Menü öffnen','close_menu'=>'Menü schließen','home'=>'Startseite','back_to_home'=>'Zur Startseite','read_more'=>'Weiterlesen','all'=>'Alle','loading'=>'Lädt','language'=>'Sprache','change_language'=>'Sprache wechseln','pagination'=>'Seiten','table_of_contents'=>'Auf dieser Seite','reading_time'=>':minutes Min. Lesezeit','breadcrumb'=>'Navigationspfad',
 'services'=>'Leistungen','locations'=>'Regionen','sectors'=>'Branchen','projects'=>'Beispielseiten','blog'=>'Blog','faq'=>'Häufige Fragen','contact'=>'Kontakt','about'=>'Über uns','prices'=>'Preise','published_on'=>'Veröffentlicht','updated_on'=>'Aktualisiert','category'=>'Kategorie','sector'=>'Branche','district'=>'Bezirk','client'=>'Kunde','visit_site'=>'Website besuchen','related_projects'=>'Ähnliche Beispiele','latest_posts'=>'Neueste Beiträge','other_services'=>'Weitere Leistungen','other_sectors'=>'Weitere Branchen','nearby_locations'=>'Weitere Regionen','quick_facts'=>'Kurzinfos','no_results'=>'Keine Einträge gefunden.',
 'request_quote'=>'Angebot für Ihr Projekt','quote_card_text'=>'Beschreiben Sie kurz Ihren Bedarf; gemeinsam klären wir die passende Lösung und den nächsten Schritt.','whatsapp'=>'WhatsApp','write_on_whatsapp'=>'Nachricht senden','contact_details'=>'Kontaktdaten',
 'form_name'=>'Name','form_phone'=>'Telefon','form_email'=>'E-Mail','form_service'=>'Gewünschte Leistung','form_message'=>'Ihre Nachricht','form_kvkk'=>'Ich habe die Datenschutzhinweise gelesen.','form_submit'=>'Angebot anfordern','form_sending'=>'Wird gesendet','form_choose'=>'Bitte wählen','form_required'=>'Pflichtfeld','form_error_title'=>'Das Formular konnte nicht gesendet werden','form_error_text'=>'Bitte prüfen Sie die Felder und versuchen Sie es erneut.','form_success'=>'Vielen Dank — wir melden uns in Kürze.',
 'phone'=>'Telefon','email'=>'E-Mail','address'=>'Adresse','opening_hours'=>'Öffnungszeiten','follow_us'=>'Folgen Sie uns','error_404_title'=>'Seite nicht gefunden','error_404_text'=>'Die gesuchte Seite wurde verschoben oder entfernt.','error_500_title'=>'Ein Fehler ist aufgetreten','error_419_title'=>'Sitzung konnte nicht geprüft werden','maintenance_title'=>'Wir sind gleich zurück','all_rights'=>'Alle Rechte vorbehalten.','legal'=>'Rechtliches',
];
