<?php
/** Türkçe arayüz dizeleri (varsayılan dil). */
declare(strict_types=1);
return [
    'skip_to_content'=>'İçeriğe geç','menu'=>'Menü','open_menu'=>'Menüyü aç','close_menu'=>'Menüyü kapat','home'=>'Anasayfa','back_to_home'=>'Anasayfaya dön','read_more'=>'Devamını oku','all'=>'Tümü','loading'=>'Yükleniyor','language'=>'Dil','change_language'=>'Dil değiştir','pagination'=>'Sayfalar','table_of_contents'=>'İçindekiler','reading_time'=>':minutes dk okuma','breadcrumb'=>'Sayfa yolu',
    'services'=>'Hizmetler','locations'=>'Bölgeler','sectors'=>'Sektörler','projects'=>'Örnek Siteler','blog'=>'Blog','faq'=>'Sık sorulan sorular','contact'=>'İletişim','about'=>'Hakkımızda','prices'=>'Fiyatlar','published_on'=>'Yayın tarihi','updated_on'=>'Güncelleme','category'=>'Kategori','sector'=>'Sektör','district'=>'İlçe','client'=>'Müşteri','visit_site'=>'Siteyi ziyaret et','related_projects'=>'Benzer örnekler','latest_posts'=>'Son yazılar','other_services'=>'Diğer hizmetler','other_sectors'=>'Diğer sektörler','nearby_locations'=>'Diğer hizmet bölgeleri','quick_facts'=>'Hızlı bilgiler','no_results'=>'Kayıt bulunamadı.','view_project'=>'Örneği incele','area_graphic_note'=>'Bağlantı çizgisi hizmet bölgelerini temsili olarak gösterir; coğrafi sınır değildir.',
    'request_quote'=>'Projeniz için teklif alın','quote_card_text'=>'İhtiyacınızı kısaca anlatın; uygun çözümü ve sonraki adımı birlikte netleştirelim.','whatsapp'=>'WhatsApp','write_on_whatsapp'=>'Mesaj gönder','contact_details'=>'İletişim bilgileri',
    'form_name'=>'Ad soyad','form_phone'=>'Telefon','form_email'=>'E-posta','form_service'=>'İlgilendiğiniz hizmet','form_message'=>'Mesajınız','form_kvkk'=>'Kişisel verilerimin işlenmesine ilişkin aydınlatma metnini okudum.','form_submit'=>'Teklif isteyin','form_sending'=>'Gönderiliyor','form_choose'=>'Seçiniz','form_required'=>'Zorunlu alan','form_error_title'=>'Formu gönderemedik','form_error_text'=>'Aşağıdaki alanları kontrol edip tekrar deneyin.','form_success'=>'Mesajınız alındı. En kısa sürede dönüş yapacağız.',
    'phone'=>'Telefon','email'=>'E-posta','address'=>'Adres','opening_hours'=>'Çalışma saatleri','follow_us'=>'Bizi takip edin',
    'error_404_title'=>'Sayfa bulunamadı','error_404_text'=>'Aradığınız sayfa taşınmış veya kaldırılmış olabilir.','error_500_title'=>'Beklenmeyen bir hata oluştu','error_419_title'=>'Oturum doğrulanamadı','maintenance_title'=>'Kısa bir ara veriyoruz','all_rights'=>'Tüm hakları saklıdır.','legal'=>'Yasal',
];
