<?php
/** Türkçe arayüz dizeleri (varsayılan dil). */
declare(strict_types=1);
return [
    'skip_to_content'=>'İçeriğe geç','menu'=>'Menü','open_menu'=>'Menüyü aç','close_menu'=>'Menüyü kapat','home'=>'Anasayfa','back_to_home'=>'Anasayfaya dön','read_more'=>'Devamını oku','all'=>'Tümü','loading'=>'Yükleniyor','language'=>'Dil','change_language'=>'Dil değiştir','pagination'=>'Sayfalar','table_of_contents'=>'İçindekiler','reading_time'=>':minutes dk okuma','breadcrumb'=>'Sayfa yolu',
    'services'=>'Hizmetler','locations'=>'Bölgeler','sectors'=>'Sektörler','projects'=>'Örnek Siteler','blog'=>'Blog','faq'=>'Sık sorulan sorular','contact'=>'İletişim','about'=>'Hakkımızda','prices'=>'Fiyatlar','published_on'=>'Yayın tarihi','updated_on'=>'Güncelleme','category'=>'Kategori','sector'=>'Sektör','district'=>'İlçe','client'=>'Müşteri','visit_site'=>'Siteyi ziyaret et','related_projects'=>'Benzer örnekler','latest_posts'=>'Son yazılar','other_services'=>'Diğer hizmetler','other_sectors'=>'Diğer sektörler','nearby_locations'=>'Diğer hizmet bölgeleri','quick_facts'=>'Hızlı bilgiler','no_results'=>'Kayıt bulunamadı.','view_project'=>'Örneği incele','area_graphic_note'=>'Bağlantı çizgisi hizmet bölgelerini temsili olarak gösterir; coğrafi sınır değildir.',
    'request_quote'=>'Projeniz için teklif alın','quote_card_text'=>'İhtiyacınızı kısaca anlatın; uygun çözümü ve sonraki adımı birlikte netleştirelim.','whatsapp'=>'WhatsApp','write_on_whatsapp'=>'Mesaj gönder','contact_details'=>'İletişim bilgileri',
    'form_name'=>'Ad soyad','form_phone'=>'Telefon','form_email'=>'E-posta','form_service'=>'İlgilendiğiniz hizmet','form_message'=>'Mesajınız','form_kvkk'=>'Kişisel verilerimin işlenmesine ilişkin aydınlatma metnini okudum.','form_submit'=>'Teklif isteyin','form_sending'=>'Gönderiliyor','form_choose'=>'Seçiniz','form_required'=>'Zorunlu alan','form_error_title'=>'Formu gönderemedik','form_error_text'=>'Aşağıdaki alanları kontrol edip tekrar deneyin.','form_success'=>'Mesajınız alındı. En kısa sürede dönüş yapacağız.',
    'phone'=>'Telefon','email'=>'E-posta','address'=>'Adres','opening_hours'=>'Çalışma saatleri','follow_us'=>'Bizi takip edin',
    'error_404_title'=>'Sayfa bulunamadı','error_404_text'=>'Aradığınız sayfa taşınmış veya kaldırılmış olabilir.','error_500_title'=>'Beklenmeyen bir hata oluştu','error_419_title'=>'Oturum doğrulanamadı','maintenance_title'=>'Kısa bir ara veriyoruz','all_rights'=>'Tüm hakları saklıdır.','legal'=>'Yasal',

    // Referans ana sayfa arayüzü
    'service_benefits'=>'Hizmet avantajları','free_consultation'=>'Ücretsiz Ön Görüşme','quick_reply'=>'Hızlı Geri Dönüş','tailored_solution'=>'Size Özel Çözüm',
    'technology_for_limits'=>'Sınırların ötesi için teknoloji','core_capabilities'=>'Temel yetkinlikler','custom_design'=>'Özel Tasarım','custom_design_short'=>'İşletmenize özel arayüz','mobile_first'=>'Mobil Uyum','mobile_first_short'=>'Her ekranda kusursuz deneyim','speed_and_seo'=>'Hız & SEO','speed_and_seo_short'=>'Teknik performans odaklı','continuous_support'=>'Sürekli Destek','continuous_support_short'=>'Yayın sonrası da yanınızda',
    'our_services'=>'Hizmetlerimiz','all_services'=>'Tüm Hizmetleri Gör','more_details'=>'Detayları Gör','featured_projects'=>'Öne Çıkan Projeler','all_projects'=>'Tüm Projeleri Gör','how_we_work'=>'Nasıl Çalışıyoruz?','transparent_process'=>'Şeffaf, ölçülebilir ve adım adım ilerleyen süreç.','why_arcates'=>'Neden ARCATES?','why_arcates_short'=>'İşi yalnızca teslim etmiyor, doğru dijital temeli birlikte kuruyoruz.','more_than_software'=>'Yazılımdan fazlası: işinize uygun dijital çözüm.','who_we_are'=>'Biz Kimiz?','human_centered_technology'=>'Teknolojiyi anlaşılır, hızlı ve işletmeye fayda sağlayan hale getiriyoruz.','team_image_alt'=>'Arcates Yazılım ekibi çalışma toplantısında','learn_more_about_us'=>'Bizi Daha Yakından Tanıyın','latest_articles'=>'Son Yazılar','latest_articles_short'=>'Web, yazılım, performans ve dijital büyüme üzerine güncel içerikler.','all_posts'=>'Tüm Yazıları Gör','turn_ideas_into_reality'=>'Fikirlerinizi gerçeğe dönüştürelim',
];
